### ISSUE TITLE
Does this work with Arduino Uno R4 WiFi?

### ISSUE THREAD

**Issue by OscarSheng** [asukiaaa/arduino-XboxSeriesXControllerESP32#10]
I'm a newcomer to the Arduino world. I want to connect my board with a Xbox Controller (Model 1914). I installed the library in Arduino IDE, when I try to compile, it says "ext_nimble_config.h: No such file or directory". How to fix it?

**Comment by asukiaaa** [comment]
No.
This library was written for ESP32 with BLE.
Arduino Uno does not have BLE so the library does not support it.

**Comment by OscarSheng** [comment]
> No. This library was written for ESP32 with BLE. Arduino Uno does not have BLE so the library does not support it.

There Uno R4 WiFi is a new Uno board which has a built-in ESP32-S3 chip.

**Comment by asukiaaa** [comment]
I understood that Uno R4 WiFi has an ESP32-S3 and it can controll by Arduino BLE.
https://www.arduino.cc/reference/en/libraries/arduinoble/

The library supports subscribing notification so it might communicate with controller of xbox.
However, NimBLE arduino does not support Arduino Uno R4 WiFi so this library also does not support the Uno R4 WiFi
https://github.com/h2zero/NimBLE-Arduino/issues/621

Arduino Uno R4 WiFi has possibility to use controller of xbox but we need to create other library to do that.
