### ISSUE TITLE
Compatibility with Uno R4 WiFi

### ISSUE THREAD

**Issue by DaniBoie** [asukiaaa/arduino-XboxSeriesXControllerESP32#11]
When attempting to upload the example connect sketch I get faced with a compilation error, the issue is discussed briefly in https://github.com/h2zero/NimBLE-Arduino/issues/622 and seems to be an issue of the R4 WiFi indirectly communicating with the ESP module. What microcontroller was used for development of the library, and is this something that can be easily addressed?

THE ERROR:

In file included from c:\Users\Danny\Documents\Arduino\libraries\NimBLE-Arduino\src/NimBLEDevice.h:18:0,
                 from c:\Users\Danny\Documents\Arduino\libraries\XboxSeriesXControllerESP32_asukiaaa\src/XboxSeriesXControllerESP32_asukiaaa.hpp:3,
                 from C:\Users\Danny\AppData\Local\Temp\.arduinoIDE-unsaved2024728-18444-c9n3fy.q4c84\connect\connect.ino:1:
c:\Users\Danny\Documents\Arduino\libraries\NimBLE-Arduino\src/nimconfig.h:6:10: fatal error: ext_nimble_config.h: No such file or directory
 #include "ext_nimble_config.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1

**Comment by asukiaaa** [comment]
This library support ESP32 not for Arduino Uno.

**Comment by asukiaaa** [comment]
If you want to use XboxController with Arduino Uno, you should use another ESP32 with the following library.
https://github.com/asukiaaa/arduino-ControllerAsI2c
Use the ESP32 as a receiver for controller of xbox and handle the information by Arduino Uno via I2C.

**Comment by DaniBoie** [comment]
If I am using a Arduino Uno R4 (with the integrated ESP32 chip) is there
any way I can use that same ESP32 Chip that is on the board?

**Comment by asukiaaa** [comment]
I understood that Uno R4 WiFi has an ESP32S3 but we need other library that uses Arduino BLE.
https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32/issues/10#issuecomment-2319714608

**Comment by DaniBoie** [comment]
Thanks for all your help!

I'll dig deeper and probably start developing a library if I can to make it
easier for others. If I had questions regarding BLE and Xbox Controller
communication profiles could I reach out to you?
