### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Taha-Firoz** [asukiaaa/arduino-XboxSeriesXControllerESP32#2]
Same issue as you've detailed in your issue [here](https://github.com/h2zero/NimBLE-Arduino/issues/172) esp reports the controller connected and char's read but led continues to blink

Edit: I tried to adapt this code to run on IDF and I was having the problem above. I tried the Arduino only version and that worked can you help me in fixing this for esp-idf

**Comment by Taha-Firoz** [comment]
You have to read from a particular set of characteristics to complete the pairing.

**Comment by asukiaaa** [comment]
I cannot follow the problem but you may resolve the problem by your self.
Do you need reading characteristic of HID?
https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32/blob/b311a0c96af33ee39a2df68911c4e27df4344ecd/src/XboxSeriesXControllerESP32_asukiaaa.hpp#L322
