### ISSUE TITLE
multiple definition of `XboxSeriesXControllerESP32_asukiaaa::controllerAppearance' error

### ISSUE THREAD

**Issue by geekli** [asukiaaa/arduino-XboxSeriesXControllerESP32#5]
Referencing `#include <XboxSeriesXControllerESP32_asukiaaa.hpp>`in multiple files will cause *multiple definition errors*；

so can those  variables be declared  as `static`  or `class static constant`?
 

```C++
static uint16_t controllerAppearance = 964;
static String controllerManufacturerDataNormal = "060000";
static String controllerManufacturerDataSearching = "0600030080";
```

**Comment by asukiaaa** [comment]
Thank you for the information.
I changed the definition with using static const and released 1.0.9.
https://github.com/asukiaaa/arduino-XboxSeriesXControllerESP32/commit/9b0916bce465b6eef6f2bfc3d4d1e39c8bb491ba
